version: '3.9'

services:

  react-server-crash-course:
    image: react-server-crash-course
    build:
      context: ./
      dockerfile: Dockerfile.server
    ports:
      - 5000:5000
      
  react-crash-course:
    image: react-crash-course
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000